title: XPOC framework site
#description: Resources for the Cross-Platform Origin of Content (XPOC) framework
#theme: jekyll-theme-minimal
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
