title: Cross-Platform Origin of Content (XPOC) resources
description: Cross-Platform Origin of Content (XPOC) resources
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
