name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sample: [client-side-html]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      # Cache for samples directory
      - name: Cache Node.js modules for samples
        uses: actions/cache@v2
        with:
          path: samples/${{ matrix.sample }}/node_modules
          key: ${{ runner.os }}-build-${{ matrix.sample }}-${{ hashFiles('samples/${{ matrix.sample }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.sample }}-

      - name: Install Dependencies for samples
        run: |
          cd samples/${{ matrix.sample }}
          npm install

      - name: Start Server and Check
        run: |
          cd samples/${{ matrix.sample }}
          npm run start &
          sleep 10 # wait for 10 seconds to ensure server starts
          # Now, kill the server (running on port 3000 in our samples):
          kill -9 $(lsof -t -i:3000)

      # Cache for lib directory
      - name: Cache Node.js modules for lib
        uses: actions/cache@v2
        with:
          path: lib/node_modules
          key: ${{ runner.os }}-build-lib-${{ hashFiles('./lib/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-lib-

      - name: Install Dependencies for lib
        run: |
          cd lib
          npm install

      - name: Build for lib
        run: |
          cd lib
          npm run build

      - name: Test for lib
        run: |
          cd lib
          npm test
