name: Deploy Server Backend to AKS
on:
  workflow_dispatch:
  
jobs:
  deploy-server-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}

    - name: Build and rollout to CI
      run: |
        cd samples/server-backend
        docker build ${{ secrets.CONTAINER_REGISTRY }}/xpoc-server-backend:latest \
          -f ./Dockerfile ../..
        docker push ${{ secrets.CONTAINER_REGISTRY }}/xpoc-server-backend:latest
        kubectl -n xpoc-server-ns rollout restart deployment/xpoc-server
